version: '3.9'

services:
  db:
    image: postgres:13.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'flask'
